# Generated by Django 5.0.2 on 2024-02-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_product_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='content',
            field=models.TextField(),
        ),
    ]
