# Generated by Django 5.0.2 on 2024-02-22 13:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_editor_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
