# Generated by Django 5.0.2 on 2024-02-22 13:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_editor_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
