# Generated by Django 5.0.2 on 2024-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_room_roommember_delete_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='userEmail',
            field=models.CharField(max_length=100),
        ),
    ]
