# Generated by Django 5.0.2 on 2024-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_document_created_by_docmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
