# Generated by Django 5.0.2 on 2024-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_document_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmember',
            name='userEmail',
            field=models.CharField(max_length=100),
        ),
    ]
